name: nafausa
description: "Nepalis And Friends Association Arizona mobile app"
publish_to: 'none'

version: 1.0.0+8

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.5
  sembast: ^3.8.5+1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  get: ^4.7.2
  equatable: ^2.0.7
  connectivity_plus: ^6.1.4
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  dio_curl_logger: ^1.2.0
  lottie: ^3.3.1
  http: ^1.4.0
  firebase_auth: ^6.0.0
  get_it: ^8.2.0
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  oktoast: ^3.4.0
  flutter_timezone: ^4.1.1
  device_info_plus: ^11.5.0
  google_fonts: ^6.3.0
  vibration: ^3.1.3
  country: ^6.0.1
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_widget_from_html: ^0.17.0
  skeletonizer: ^2.1.0+1
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_pdfviewer: ^30.2.5
  file_saver: ^0.3.1
  file_picker: ^10.3.1
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  image_gallery_saver_plus: ^4.0.1
  firebase_core: ^4.0.0
  chewie: ^1.12.1
  video_player: ^2.10.0
  add_2_calendar_new: ^1.0.4
  font_awesome_flutter: ^10.9.1
  cached_video_player_plus: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/
    - assets/animations/


